export const countries = [
    { id: "us", name: "United States" },
    { id: "uk", name: "United Kingdom" },
    { id: "ca", name: "Canada" },
    { id: "au", name: "Australia" },
    { id: "de", name: "Germany" },
    { id: "fr", name: "France" },
    { id: "it", name: "Italy" },
    { id: "es", name: "Spain" },
    { id: "nl", name: "Netherlands" },
    { id: "be", name: "Belgium" },
    { id: "ch", name: "Switzerland" },
    { id: "at", name: "Austria" },
    { id: "se", name: "Sweden" },
    { id: "no", name: "Norway" },
    { id: "dk", name: "Denmark" },
    { id: "fi", name: "Finland" },
    { id: "ie", name: "Ireland" },
    { id: "pt", name: "Portugal" },
    { id: "pl", name: "Poland" },
    { id: "cz", name: "Czech Republic" },
    { id: "in", name: "India" },
    { id: "cn", name: "China" },
    { id: "jp", name: "Japan" },
    { id: "kr", name: "South Korea" },
    { id: "sg", name: "Singapore" },
    { id: "nz", name: "New Zealand" },
    { id: "mx", name: "Mexico" },
    { id: "br", name: "Brazil" },
    { id: "ar", name: "Argentina" },
    { id: "za", name: "South Africa" },
  ];

export const strengthColors = { "Too weak": "red.500", Weak: "orange.500", Medium: "yellow.500", Strong: "green.500" };